### ISSUE TITLE
Azure: Reusing existing resources

### ISSUE THREAD

**Issue by vinseon** [ow2-proactive/connector-iaas#41]
- Attach to an existing public IP address (if not already attached!)
- Attach to an existing security group
- Attach to an existing virtual network

**Comment by gheon** [comment]
The second point ("Attach to an existing security group") is done in the PR: https://github.com/ow2-proactive/connector-iaas/pull/46

**Comment by vinseon** [comment]
Issue fixed:
- https://github.com/ow2-proactive/connector-iaas/pull/46: security group
- https://github.com/ow2-proactive/connector-iaas/commit/f91eb15ec136f37f7c1e7f133ef1acb5c72d50bc: virtual network attachement
- https://github.com/ow2-proactive/connector-iaas/commit/b867861514019ea23daeb0f97d63c881d7a6b0b3: public IP address
